### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by nishnash54** [mdh30/OCR#4]
#### Tasks
 - [x] Integrate Yandex API
 - [x] Translate English to Spanish
 - [ ] Translate English to French

**Comment by nishnash54** [comment]
Completed
Requires some testing
